<?php

namespace AssoSport\ProjetBundle\Repository;

/**
 * ProfilProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilProjetRepository extends \Doctrine\ORM\EntityRepository
{
}
