asso_sport_accueil_homepage:
    path:     /
    defaults: { _controller: AssoSportAccueilBundle:Accueil:home }

#asso_sport_accueil_test:
    #path:     /manuel
    #defaults: { _controller: AssoSportAccueilBundle:Utilisateur:print }

#asso_sport_accueil_recherche:
    #path:     /recherche
    #defaults: { _controller: AssoSportAccueilBundle:Utilisateur:trouve }
    #requirements:
        #id:   \d+

asso_sport_accueil_formulaire:
    path:     /inscription
    defaults: { _controller: AssoSportAccueilBundle:Utilisateur:formulaire }

#asso_sport_accueil_connect:
    #path:     /connect
    #defaults: { _controller: AssoSportAccueilBundle:Utilisateur:connect }

asso_sport_accueil_projet:
    path:     /inscription/projet
    defaults: { _controller: AssoSportAccueilBundle:Utilisateur:inscription }

asso_sport_accueil_a_propos:
    path:     /apropos
    defaults: { _controller: AssoSportAccueilBundle:Accueil:aPropos }
