asso_sport_admin_homepage:
    path:     /
    defaults: { _controller: AssoSportAdminBundle:Admin:home }

asso_sport_admin_profil:
    path:     /profil
    defaults: { _controller: AssoSportAdminBundle:Admin:profil }

asso_sport_admin_sport:
    path:     /sport
    defaults: { _controller: AssoSportAdminBundle:Admin:sport }

asso_sport_admin_projet:
    path:     /projet
    defaults: { _controller: AssoSportAdminBundle:Admin:projet }

asso_sport_admin_typesport:
    path:     /typesport
    defaults: { _controller: AssoSportAdminBundle:Admin:typesport }

asso_sport_admin_profilprojet:
    path:     /profilprojet
    defaults: { _controller: AssoSportAdminBundle:Admin:profilprojet }

asso_sport_admin_listemembresasso:
    path:     /membres/asso
    defaults: { _controller: AssoSportAdminBundle:Admin:assoliste }

asso_sport_admin_listemembresprojet:
    path:     /membres/projet
    defaults: { _controller: AssoSportAdminBundle:Admin:projetliste }

asso_sport_admin_listeall:
    path:     /membres
    defaults: { _controller: AssoSportAdminBundle:Admin:liste }

asso_sport_admin_listeactivites:
    path:     /activites
    defaults: { _controller: AssoSportAdminBundle:Admin:activites }

asso_sport_admin_listeactivitesperso:
    path:     /membres/activites/perso/{id}
    defaults: { _controller: AssoSportAdminBundle:Admin:activitesperso }
    requirements:
        id: \d* 

asso_sport_admin_listeactivitespersoprojet:
    path:     membres/activites/perso/projet/{id}
    defaults: { _controller: AssoSportAdminBundle:Admin:activitespersoprojet }
    requirements:
        id: \d* 

asso_sport_admin_distanceprojet:
    path:     /projet/distance
    defaults: { _controller: AssoSportAdminBundle:Admin:distanceprojet } 

asso_sport_admin_demandes:
    path:     /demandes
    defaults: { _controller: AssoSportAdminBundle:Admin:demandes } 

asso_sport_admin_statProjetAction:
    path:     /projet/stat
    defaults: { _controller: AssoSportAdminBundle:Admin:statProjet }

asso_sport_admin_statAdherent:
    path:     /membres/adherent/stat/{id}
    defaults: { _controller: AssoSportAdminBundle:Admin:stats } 
    requirements:
        id: \d*                    
