<?php

namespace AssoSport\AccueilBundle\Repository;

/**
 * SportsFavorisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SportsFavorisRepository extends \Doctrine\ORM\EntityRepository
{
}
