<?php

namespace AssoSport\AccueilBundle\Repository;

/**
 * TypeSportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeSportRepository extends \Doctrine\ORM\EntityRepository
{
}
